In [1]:
import numpy as np
import csv
import time
import os

In [2]:
filename = "scanfile.txt"
filepath = os.path.join("C:\\", "qudi-hira", "hardware", "nanonis", filename)

In [4]:
def get_csv_rows():
    rows = []
    with open(filepath) as f:
        csv_reader = csv.reader(f, delimiter=',')
        for idx, row in enumerate(csv_reader):
            rows.append(list(map(int, row)))
    return rows

def get_total_rows_and_cols():
    """ First row of the csv file """
    return get_csv_rows()[0]

def nanonis_running():
    rows = get_csv_rows()
    if len(rows) == 1:
        return True
    else:
        return False

def get_current_row_and_col():
    """ Last row of the csv file """
    rows = get_csv_rows()
    if len(rows) == 1:
        raise ValueError("Insuffienct data")
    else:
        return rows[-1]

In [40]:
# Start first
while True:
    if nanonis_running():
        total_rows, total_cols = get_total_rows_and_cols()
        scan_odmr_data = np.zeros((total_rows, total_cols, 5))

        row, col = 0, 0
        while True:
            try:
                current_row, current_col = get_current_row_and_col()
                #print(current_row, current_col)

                if current_row != row or current_col != col:
                    row = current_row
                    col = current_col
                if current_row == -1 and current_col == -1 :
                    break

                scan_odmr_data[row, col] += np.ones(5)

                # print("row =", row, "col =", col, "data =", scan_odmr_data[row, col])

                time.sleep(0.01)
            except ValueError as exc:
                time.sleep(0.05)
                pass
        break
    else:
        time.sleep(0.005)

# Data Processing

In [42]:
np.shape(scan_odmr_data)

(2, 3, 5)

In [45]:
scan_odmr_data

array([[[96., 96., 96., 96., 96.],
        [98., 98., 98., 98., 98.],
        [97., 97., 97., 97., 97.]],

       [[97., 97., 97., 97., 97.],
        [99., 99., 99., 99., 99.],
        [97., 97., 97., 97., 97.]]])

In [54]:
x_dim, y_dim, sweep_size = np.shape(scan_odmr_data)

for item in scan_odmr_data.reshape(x_dim * y_dim, sweep_size):
    print(item)
    # 1. Fit Lorentzian to each array
    # 2. Extract splitting
    # 3. Plot splitting in 2D map

[96. 96. 96. 96. 96.]
[98. 98. 98. 98. 98.]
[97. 97. 97. 97. 97.]
[97. 97. 97. 97. 97.]
[99. 99. 99. 99. 99.]
[97. 97. 97. 97. 97.]


In [62]:
np.shape(scan_odmr_data.reshape(x_dim * y_dim, sweep_size))

(6, 5)

In [56]:
np.savetxt("arr.csv", scan_odmr_data.reshape(x_dim * y_dim, sweep_size), delimiter=',')

In [57]:
np.save("arr.npy", scan_odmr_data)

In [61]:
np.shape(np.load("arr.npy"))

(2, 3, 5)

In [64]:
from itertools import product


In [74]:
x_size, y_size = 2, 2

scan_odmr_data = np.zeros((x_size, y_size, 5))

for x, y in product(np.arange(x_size), np.arange(y_size)):
    print(x, y)
    scan_odmr_data[x, y] += np.ones(5)
    np.save("arr.npy", scan_odmr_data)
    arr = np.load("arr.npy")
    print(arr)

0 0
[[[1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
0 1
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
1 0
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0.]]]
1 1
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [31]:
def get_dict():
    return {"row": 1, "col": 2}

print("The values are {0} {1}".format(*get_dict().values()))

The values are 1 2


In [10]:
import numpy as np

In [13]:
data = {"freq": np.linspace(2.8e9, 3e9, 100), "counts": np.zeros((5, 2, 3))}
header = ""
header += str(list(data.keys()))[1:-1]
print(header)

np.savez_compressed("test", **data)

'freq', 'counts'


In [17]:
a = np.load("test.npz")

In [26]:
a["counts"][0][0]

array([0., 0., 0.])